/* Generated by convbdf on Sun Dec  1 01:06:05 2019. */
#ifdef HAVE_LCD_BITMAP

/* Font information */
#define SYSFONT_NAME           unifont
#define SYSFONT_FACENAME       -gnu-unifont-medium-r-normal--16-160-75-75-c-80-iso10646-1
#define SYSFONT_WIDTH          16
#define SYSFONT_HEIGHT         16
#define SYSFONT_SIZE           65534
#define SYSFONT_ASCENT         14
#define SYSFONT_DEPTH          0
#define SYSFONT_DESCENT        2
#define SYSFONT_FIRST_CHAR     0
#define SYSFONT_LAST_CHAR      65533
#define SYSFONT_DEFAULT_CHAR   32
#define SYSFONT_PROPORTIONAL   1
#define SYSFONT_COPYRIGHT      
#define SYSFONT_BITS_SIZE      1015136

#endif
